import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import {
  HttpTestingController,
  provideHttpClientTesting,
} from '@angular/common/http/testing';

import { ExpenseFormComponent } from './expense-form.component';
import { Expense } from '../types/expenses';
import { environment } from '../../environments/environment';

describe('ExpenseFormComponent', () => {
  let component: ExpenseFormComponent;
  let fixture: ComponentFixture<ExpenseFormComponent>;
  let httpMock: HttpTestingController;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [ExpenseFormComponent],
      providers: [provideHttpClient(), provideHttpClientTesting()],
    }).compileComponents();

    fixture = TestBed.createComponent(ExpenseFormComponent);
    component = fixture.componentInstance;
    httpMock = TestBed.inject(HttpTestingController);
    fixture.detectChanges();
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should post the new expense to the API', () => {
    const date = new Date(2026, 0, 1);
    component.currentDate = date;
    component.formData = { name: 'Internet', value: 99.9 };

    component.createNewExpense();

    const req = httpMock.expectOne(environment.apiUri + 'Expense');
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ name: 'Internet', value: 99.9, expenseDate: date });
    req.flush({ id: 42, name: 'Internet', value: 99.9, expenseDate: '2026-01-01T00:00:00' });
  });

  it('should emit the created expense only after the API confirms', () => {
    const emitted: Expense[] = [];
    component.formSubmit.subscribe((expense) => emitted.push(expense));
    component.formData = { name: 'Energia', value: 155.96 };

    component.createNewExpense();
    const req = httpMock.expectOne(environment.apiUri + 'Expense');
    expect(emitted.length).toBe(0);

    req.flush({ id: 42, name: 'Energia', value: 155.96, expenseDate: '2026-01-01T00:00:00' });

    expect(emitted.length).toBe(1);
    expect(emitted[0].name).toBe('Energia');
  });


  it('should emit the id generated by the API', () => {
    const emitted: Expense[] = [];
    component.formSubmit.subscribe((expense) => emitted.push(expense));
    component.formData = { name: 'Energia', value: 155.96 };

    component.createNewExpense();
    httpMock
      .expectOne(environment.apiUri + 'Expense')
      .flush({ id: 42, name: 'Energia', value: 155.96, expenseDate: '2026-01-01T00:00:00' });

    expect(emitted[0].id).toBe(42);
  });
});
