import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import {
  HttpTestingController,
  provideHttpClientTesting,
} from '@angular/common/http/testing';

import { ExpenseService } from './expense.service';
import { Expense, NewExpense } from '../types/expenses';
import { environment } from '../../environments/environment';

describe('ExpenseService', () => {
  let service: ExpenseService;
  let httpMock: HttpTestingController;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });
    service = TestBed.inject(ExpenseService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  describe('list', () => {
    it('should GET the expenses for the given year', () => {
      service.list(2026).subscribe();

      const req = httpMock.expectOne(environment.apiUri + 'Expense?year=2026');
      expect(req.request.method).toBe('GET');
      req.flush([]);
    });
  });

  describe('create', () => {
    const newExpense: NewExpense = {
      name: 'Internet',
      value: 99.9,
      expenseDate: new Date(2026, 0, 1),
    };

    // A API monta o CreateExpenseRequestModel pelo construtor (name, value,
    // date): enviar "expenseDate" gravaria a despesa com a data padrão.
    it('should POST the expense without an id and with the date in "date"', () => {
      service.create(newExpense).subscribe();

      const req = httpMock.expectOne(environment.apiUri + 'Expense');
      expect(req.request.method).toBe('POST');
      expect(req.request.body).toEqual({
        name: 'Internet',
        value: 99.9,
        date: new Date(2026, 0, 1),
      });
      req.flush({ id: 42, name: 'Internet', value: 99.9, expenseDate: '2026-01-01T00:00:00' });
    });

    // Regressão #17: o id da despesa tem que ser o gerado pelo banco, não um
    // calculado na UI.
    it('should return the expense with the id generated by the API', () => {
      let created: Expense | undefined;
      service.create(newExpense).subscribe((expense) => (created = expense));

      httpMock.expectOne(environment.apiUri + 'Expense').flush({
        id: 42,
        name: 'Internet',
        value: 99.9,
        expenseDate: '2026-01-01T00:00:00',
        userId: 3,
      });

      expect(created).toEqual(
        jasmine.objectContaining({ id: 42, name: 'Internet', value: 99.9 })
      );
    });
  });

  describe('deleteByIds', () => {
    it('should DELETE with each id sent exactly once', () => {
      service.deleteByIds([1, 2]).subscribe();

      const req = httpMock.expectOne(
        (r) => r.url === environment.apiUri + 'Expense/DeleteByIds'
      );
      expect(req.request.method).toBe('DELETE');
      expect(req.request.params.getAll('ids')).toEqual(['1', '2']);
      req.flush({});
    });

    it('should support a single id', () => {
      service.deleteByIds([5]).subscribe();

      const req = httpMock.expectOne((r) => r.url.includes('DeleteByIds'));
      expect(req.request.params.getAll('ids')).toEqual(['5']);
      req.flush({});
    });
  });
});
